---
- name: Cleanup Splunk Logs
  hosts: all
  become: true

  vars:
    splunk_log_path: "/opt/splunkforwarder/var/log/splunk"
    log_retention_days: 7
    log_extension: "dmp"        
    exclude_log: "splunkd.log"

  tasks:

    - name: Check if Splunk log directory exists
      stat:
        path: "{{ splunk_log_path }}"
      register: log_dir

    - name: Fail if Splunk log directory does not exist
      fail:
        msg: "Splunk log directory {{ splunk_log_path }} does not exist!"
      when: not log_dir.stat.exists

    - name: Find old Splunk logs (filtered by extension)
      find:
        paths: "{{ splunk_log_path }}"
        age: "{{ log_retention_days }}d"
        patterns: "*.{{ log_extension }}"
        excludes: "{{ exclude_log }}"
        recurse: yes
      register: old_logs

    - name: Show files to be deleted (debug)
      debug:
        msg: "{{ item.path }}"
      loop: "{{ old_logs.files }}"
      when: old_logs.matched > 0

    - name: Delete old Splunk log files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_logs.files }}"
      when: old_logs.matched > 0

