---
- name: Install screen on Linux
  hosts: all
  become: true

  tasks:
    - name: Install screen package on Debian/Ubuntu
      apt:
        name: screen
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install screen package on RHEL/CentOS/Fedora
      package:
        name: screen
        state: present
      when: ansible_facts['os_family'] == "RedHat"