---
- name: Configure Time Synchronization (NTP)
  hosts: all
  become: true

  vars:
    ntp_servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org

  tasks:

  # Detect if ntp is supported

  - name: Set time service fact
    set_fact:
      ntp_supported: >-
        {{ (ansible_distribution == "Fedora" and ansible_distribution_major_version | int < 16)
         or (ansible_os_family == "RedHat" and ansible_distribution_major_version | int < 8)
         or (ansible_os_family == "Debian" and ansible_distribution_major_version | int < 10) }}

  - name: Fail if ntp is not supported
    fail:
      msg: >
        The legacy 'ntp' service is not supported on
        {{ ansible_distribution }} {{ ansible_distribution_version }}.
        Please use chrony instead.
    when: not ntp_supported 

  # Install required package

  - name: Install ntp
    package:
      name: ntp
      state: present

  # Configure ntp

  - name: Configure ntp servers
    blockinfile:
      path:  "{{ '/etc/ntp/ntp.conf' if ansible_os_family == 'Debian' else '/etc/ntp.conf' }}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      block: |
        {% for server in ntp_servers %}
        server {{ server }} iburst
        {% endfor %}
    notify: restart time service

  # Enable and start ntp service

  - name: Enable and start ntp
    systemd:
      name: "{{ 'ntpd' if ansible_os_family != 'Debian' else 'ntp' }}"
      enabled: true
      state: started

  # Verify synchronization

  - name: Check ntp peers
    command: ntpq -p
    register: ntp_status
    changed_when: false

  - name: Show ntp status
    debug:
      var: ntp_status.stdout_lines

  # Handlers

  handlers:
    - name: restart time service
      systemd:
        name: "{{ 'ntpd' if ansible_os_family != 'Debian' else 'ntp' }}"
        state: restarted