- name: Install Splunk Universal Forwarder
  hosts: all
  become: true

  vars:
    splunk_uf_rpm_url: "https://download.splunk.com/products/universalforwarder/releases/10.2.0/linux/splunkforwarder-10.2.0-d749cb17ea65.x86_64.rpm"
    splunk_home: "/opt/splunkforwarder"
    splunk_pass: "ChangeMe123!"  
  tasks:

    - name: Download UF RPM
      get_url:
        url: "{{ splunk_uf_rpm_url }}"
        dest: /opt/splunkforwarder.rpm
        mode: '0644'

    - name: Install Splunk forwarder RPM
      yum:
        name: /opt/splunkforwarder.rpm
        state: present
        disable_gpg_check: yes

    - name: Create deployment config file
      copy:
        dest: "{{ splunk_home }}/etc/system/local/deploymentclient.conf"
        content: |
          [target-broker:deploymentServer]
          targetUri = 10.93.10.135:8089
        mode: '0600'
        force: no
    
    - name: Create user-seed.conf (only if not exists)
      copy:
        dest: "{{ splunk_home }}/etc/system/local/user-seed.conf"
        content: |
          [user_info]
          USERNAME = admin
          PASSWORD = {{ splunk_pass }}
        mode: '0600'
        force: no

    - name: Start Splunk and accept license (first run only)
      command: >
        {{ splunk_home }}/bin/splunk start
        --accept-license
        --answer-yes
        --no-prompt
      args:
        creates: "{{ splunk_home }}/var/run/splunkd.pid"

    - name: Enable Splunk at boot
      command: "{{ splunk_home }}/bin/splunk enable boot-start"
      environment:
        LD_LIBRARY_PATH: ""
      args:
        creates: "/etc/systemd/system/SplunkForwarder.service"